# error_codes.py

class ErrorCodes:
    # Client-side errors (4xx)
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    CONFLICT = "CONFLICT"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"

    # Server-side errors (5xx)
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

    # Application-specific errors
    USER_DETAILS_NOT_FOUND = "USER_DETAILS_NOT_FOUND"
    RESEARCH_INTEREST_NOT_FOUND = "RESEARCH_INTEREST_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DUPLICATE_RESEARCH_INTEREST = "DUPLICATE_RESEARCH_INTEREST"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    COUNTRY_LIST_ERROR = "COUNTRY_LIST_ERROR"
