# Generated by Django 5.0.3 on 2024-07-04 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_merge_20240628_0353"),
        ("educational_organizations_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalorganizations",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="educationalorganizations",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="educationalorganizations",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="educationalorganizations",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="educationalorganizations",
            name="state_province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_state",
                to="common.state",
            ),
        ),
        migrations.AddField(
            model_name="historicaleducationalorganizations",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaleducationalorganizations",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaleducationalorganizations",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaleducationalorganizations",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicaleducationalorganizations",
            name="state_province",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.state",
            ),
        ),
        migrations.AlterField(
            model_name="educationalorganizations",
            name="country",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="historicaleducationalorganizations",
            name="country",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
