# Generated by Django 5.0.3 on 2024-07-04 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_merge_20240628_0353"),
        (
            "educational_organizations_app",
            "0002_educationalorganizations_address_line1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationalorganizations",
            name="geo_admin_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.geoadmin1",
            ),
        ),
    ]
