# Generated by Django 5.0.3 on 2024-07-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_organizations_app', '0004_educationalorganizations_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='educationalorganizations',
            name='unique_organization_details',
        ),
        migrations.RemoveField(
            model_name='educationalorganizations',
            name='country',
        ),
        migrations.RemoveField(
            model_name='educationalorganizations',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='educationalorganizations',
            name='geo_admin_1',
        ),
        migrations.RemoveField(
            model_name='educationalorganizations',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicaleducationalorganizations',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicaleducationalorganizations',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaleducationalorganizations',
            name='geo_admin_1',
        ),
        migrations.RemoveField(
            model_name='historicaleducationalorganizations',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='educationalorganizations',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicaleducationalorganizations',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='educationalorganizations',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalorganizations',
            name='under_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_organizations_app.educationalorganizationscategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='historicaleducationalorganizations',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
