# Generated by Django 5.0.3 on 2024-07-19 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_merge_20240708_2354"),
        (
            "educational_organizations_app",
            "0005_remove_educationalorganizations_unique_organization_details_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalorganizations",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="educational_organizations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="educationalorganizations",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="educational_organizations_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaleducationalorganizations",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaleducationalorganizations",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="educationalorganizations",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="educationalorganizations",
            name="under_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="educational_organizations_app.educationalorganizationscategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicaleducationalorganizations",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="educationalorganizations",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "under_category", "country_code"),
                name="unique_organization_details",
            ),
        ),
    ]
