# Generated by Django 5.0.3 on 2024-06-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country_id", models.PositiveIntegerField()),
                ("country_code", models.CharField(max_length=2)),
                ("fips_code", models.CharField(blank=True, max_length=255, null=True)),
                ("iso2", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=191, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("flag", models.BooleanField(default=True)),
                (
                    "wikiDataId",
                    models.CharField(
                        blank=True,
                        help_text="Rapid API GeoDB Cities",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country_id"], name="common_stat_country_838103_idx"
                    )
                ],
            },
        ),
    ]
