# Generated by Django 5.0.3 on 2024-06-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_countries_geoadmin1_geoadmin2_historicalcountries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
