# Generated by Django 5.0.3 on 2024-06-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "properties_name",
                    models.CharField(blank=True, max_length=46, null=True),
                ),
                (
                    "properties_charset",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
            ],
        ),
    ]
