# Generated by Django 5.0.3 on 2024-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_document_image_historicaldocument_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserdocument',
            name='use',
            field=models.CharField(choices=[('resume', 'Resume'), ('sop', 'SOP'), ('image', 'Image'), ('birth_certificate', 'Birth Certificate'), ('passport', 'Passport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='use',
            field=models.CharField(choices=[('resume', 'Resume'), ('sop', 'SOP'), ('image', 'Image'), ('birth_certificate', 'Birth Certificate'), ('passport', 'Passport')], max_length=20),
        ),
    ]
