# Generated by Django 5.0.3 on 2024-06-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_historicaluserdocument_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('image', 'IMAGE'), ('pdf', 'PDF')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='type',
            field=models.CharField(choices=[('image', 'IMAGE'), ('pdf', 'PDF')], max_length=5),
        ),
    ]
