# Generated by Django 5.0.3 on 2024-06-28 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_language"),
        ("common", "0007_alter_document_type_alter_historicaldocument_type"),
    ]

    operations = []
