# Generated by Django 5.0.3 on 2024-07-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_alter_historicaluserdocument_use_and_more"),
        ("common", "0009_skilloptions_historicalskilloptions"),
    ]

    operations = []
