# Generated by Django 5.0.3 on 2024-07-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_historicaluserdocument_use_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserdocument",
            name="use",
            field=models.CharField(
                choices=[
                    ("resume", "Resume"),
                    ("sop", "SOP"),
                    ("image", "Image"),
                    ("organization_logo", "Image"),
                    ("birth_certificate", "Birth Certificate"),
                    ("passport", "Passport"),
                    ("test_score_document", "Test Score Document"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="use",
            field=models.CharField(
                choices=[
                    ("resume", "Resume"),
                    ("sop", "SOP"),
                    ("image", "Image"),
                    ("organization_logo", "Image"),
                    ("birth_certificate", "Birth Certificate"),
                    ("passport", "Passport"),
                    ("test_score_document", "Test Score Document"),
                ],
                max_length=20,
            ),
        ),
    ]
