# Generated by Django 5.0.3 on 2024-08-29 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0013_historicaluser"),
        ("college_app", "0001_initial"),
        ("common", "0013_organizationcollegegroup"),
        (
            "educational_organizations_app",
            "0007_alter_educationalorganizations_under_category",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="college_app.college",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="educational_organizations_app.educationalorganizations",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
            options={
                "unique_together": {("name", "organization", "college")},
            },
        ),
        migrations.DeleteModel(
            name="OrganizationCollegeGroup",
        ),
    ]
