# Generated by Django 5.0.3 on 2024-08-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_customgroup_delete_organizationcollegegroup"),
        (
            "educational_organizations_app",
            "0007_alter_educationalorganizations_under_category",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgroup",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="educational_organizations_app.educationalorganizations",
            ),
        ),
    ]
