# Generated by Django 5.0.3 on 2024-08-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college_app", "0001_initial"),
        ("common", "0012_alter_historicaluserdocument_use_and_more"),
        ("department_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="department",
            name="unique_department_details",
        ),
        migrations.RemoveField(
            model_name="department",
            name="campus",
        ),
        migrations.RemoveField(
            model_name="historicaldepartment",
            name="campus",
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "college"),
                name="unique_department_details",
            ),
        ),
    ]
