# Generated by Django 5.0.3 on 2024-08-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department_app", "0002_remove_department_unique_department_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="degrees_offered",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of degrees offered",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="degrees_offered",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of degrees offered",
                null=True,
            ),
        ),
    ]
