# Generated by Django 5.0.3 on 2024-08-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department_app", "0003_department_degrees_offered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="degrees_offered",
            field=models.TextField(
                default="", help_text="Comma-separated list of degrees offered"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldepartment",
            name="degrees_offered",
            field=models.TextField(
                default="", help_text="Comma-separated list of degrees offered"
            ),
        ),
    ]
