# Generated by Django 5.0.3 on 2024-06-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontactus",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
