# Generated by Django 5.0.3 on 2024-05-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_userotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userotp",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
