# Generated by Django 5.0.3 on 2024-05-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_historicalpasswordresettoken_historicaluserotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserotp",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userotp",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
