# Generated by Django 5.0.3 on 2024-05-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_historicaluserotp_deleted_at_userotp_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpasswordresettoken",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
