# Generated by Django 5.0.3 on 2024-06-17 00:19

import django.db.models.deletion
import django_countries.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUserDetails",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "city_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_language", models.TextField(blank=True, null=True)),
                ("military_status", models.JSONField(blank=True, null=True)),
                (
                    "parental_college_graduation_status",
                    models.BooleanField(default=False),
                ),
                ("hispanic_latino_origin", models.BooleanField(blank=True, null=True)),
                ("citizenship_status", models.JSONField(blank=True, null=True)),
                (
                    "country_of_citizenship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dual_citizenship", models.BooleanField(default=False)),
                (
                    "legal_state_of_residence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "visa_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("current_city", models.IntegerField(blank=True, null=True)),
                ("current_state_province", models.IntegerField(blank=True, null=True)),
                (
                    "current_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("current_country", models.IntegerField(blank=True, null=True)),
                ("permanent_address_status", models.BooleanField(default=False)),
                (
                    "permanent_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "permanent_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("permanent_city", models.IntegerField(blank=True, null=True)),
                (
                    "permanent_state_province",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "permanent_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("permanent_country", models.IntegerField(blank=True, null=True)),
                ("ethnicity", models.CharField(blank=True, max_length=255, null=True)),
                ("currently_enrolled", models.BooleanField(default=False)),
                (
                    "emergency_fname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_lname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("emergency_city", models.TextField(blank=True, null=True)),
                (
                    "emergency_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "emergency_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_relation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("acknowledgement", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user details",
                "verbose_name_plural": "historical user detailss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "city_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_language", models.TextField(blank=True, null=True)),
                ("military_status", models.JSONField(blank=True, null=True)),
                (
                    "parental_college_graduation_status",
                    models.BooleanField(default=False),
                ),
                ("hispanic_latino_origin", models.BooleanField(blank=True, null=True)),
                ("citizenship_status", models.JSONField(blank=True, null=True)),
                (
                    "country_of_citizenship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dual_citizenship", models.BooleanField(default=False)),
                (
                    "legal_state_of_residence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "visa_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("current_city", models.IntegerField(blank=True, null=True)),
                ("current_state_province", models.IntegerField(blank=True, null=True)),
                (
                    "current_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("current_country", models.IntegerField(blank=True, null=True)),
                ("permanent_address_status", models.BooleanField(default=False)),
                (
                    "permanent_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "permanent_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("permanent_city", models.IntegerField(blank=True, null=True)),
                (
                    "permanent_state_province",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "permanent_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("permanent_country", models.IntegerField(blank=True, null=True)),
                ("ethnicity", models.CharField(blank=True, max_length=255, null=True)),
                ("currently_enrolled", models.BooleanField(default=False)),
                (
                    "emergency_fname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_lname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("emergency_city", models.TextField(blank=True, null=True)),
                (
                    "emergency_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "emergency_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_relation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("acknowledgement", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "research_interests_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.researchinterestoptions",
                    ),
                ),
                (
                    "user_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_interests",
                        to="profile_app.userdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Interest",
                "verbose_name_plural": "Research Interests",
            },
        ),
        migrations.CreateModel(
            name="HistoricalVisa",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("visa_type", models.CharField(max_length=100)),
                ("issuing_country", django_countries.fields.CountryField(max_length=2)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_details",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="profile_app.userdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical visa",
                "verbose_name_plural": "historical visas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResearchInterest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "research_interests_option",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="common.researchinterestoptions",
                    ),
                ),
                (
                    "user_details",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="profile_app.userdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Research Interest",
                "verbose_name_plural": "historical Research Interests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCitizenship",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "legal_state_of_residence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_details",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="profile_app.userdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Citizenship",
                "verbose_name_plural": "historical Citizenships",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Citizenship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "legal_state_of_residence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citizenships",
                        to="profile_app.userdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Citizenship",
                "verbose_name_plural": "Citizenships",
            },
        ),
        migrations.CreateModel(
            name="Visa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visa_type", models.CharField(max_length=100)),
                ("issuing_country", django_countries.fields.CountryField(max_length=2)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "user_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visas",
                        to="profile_app.userdetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
