# Generated by Django 5.0.3 on 2024-06-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserdetails",
            name="current_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicaluserdetails",
            name="current_country",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="historicaluserdetails",
            name="permanent_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicaluserdetails",
            name="permanent_country",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="current_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="current_country",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="permanent_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="permanent_country",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
