# Generated by Django 5.0.3 on 2024-06-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_state"),
        ("profile_app", "0002_alter_historicaluserdetails_current_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserdetails",
            name="current_state_province",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.state",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserdetails",
            name="permanent_state_province",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.state",
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="current_state_province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_state",
                to="common.state",
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="permanent_state_province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permanent_state",
                to="common.state",
            ),
        ),
    ]
