# Generated by Django 5.0.3 on 2024-06-27 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_language"),
        ("profile_app", "0004_historicaluserdetails_ethnicity_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserdetails",
            name="other_languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="other_languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicaluserdetails",
            name="first_language",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.language",
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="first_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.language",
            ),
        ),
    ]
