# Generated by Django 5.0.3 on 2024-06-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0002_dissertation_historicaldissertation"),
        ("profile_app", "0003_alter_educationalbackground_options_and_more"),
        ("profile_app", "0005_historicaluserdetails_other_languages_and_more"),
    ]

    operations = []
