# Generated by Django 5.0.3 on 2024-06-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0002_historicalresearchexperience_researchexperience"),
        ("profile_app", "0006_merge_20240627_2323"),
    ]

    operations = []
