# Generated by Django 5.0.3 on 2024-07-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0008_awardgrantscholarship_and_more"),
        ("profile_app", "0008_historicalpublication_publication"),
        ("profile_app", "0008_historicalskill_skill"),
        ("profile_app", "0008_historicaltrainingworkshop_trainingworkshop"),
        ("profile_app", "0008_historicalworkexperience_workexperience"),
    ]

    operations = []
