# Generated by Django 5.0.3 on 2024-07-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0008_historicalvolunteeractivity_volunteeractivity"),
        ("profile_app", "0009_merge_20240708_2354"),
    ]

    operations = []
