# Generated by Django 5.0.3 on 2024-07-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0010_merge_20240726_0444"),
        ("profile_app", "0012_historicaltestscore_testscore"),
    ]

    operations = []
