# Generated by Django 5.0.3 on 2024-07-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0013_merge_20240726_2036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreferenceinfo",
            name="title",
            field=models.CharField(
                choices=[
                    ("Dr.", "Dr."),
                    ("Mr.", "Mr."),
                    ("Mrs.", "Mrs."),
                    ("Ms.", "Ms."),
                    ("Prof.", "Prof."),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="referenceinfo",
            name="title",
            field=models.CharField(
                choices=[
                    ("Dr.", "Dr."),
                    ("Mr.", "Mr."),
                    ("Mrs.", "Mrs."),
                    ("Ms.", "Ms."),
                    ("Prof.", "Prof."),
                ],
                max_length=50,
            ),
        ),
    ]