# Generated by Django 5.0.3 on 2024-07-30 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_alter_historicaluserdocument_use_and_more"),
        ("profile_app", "0014_alter_historicalreferenceinfo_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltestscore",
            name="user",
        ),
        migrations.RemoveField(
            model_name="testscore",
            name="user",
        ),
        migrations.AddField(
            model_name="historicaltestscore",
            name="user_details",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="profile_app.userdetails",
            ),
        ),
        migrations.AddField(
            model_name="testscore",
            name="user_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_score",
                to="profile_app.userdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testscore",
            name="user_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.userdocument",
            ),
        ),
    ]
