# Generated by Django 5.0.3 on 2024-08-14 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_alter_historicaluserdocument_use_and_more"),
        ("profile_app", "0015_remove_historicaltestscore_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citizenship",
            name="country",
        ),
        migrations.RemoveField(
            model_name="citizenship",
            name="legal_state_of_residence",
        ),
        migrations.RemoveField(
            model_name="historicalcitizenship",
            name="country",
        ),
        migrations.RemoveField(
            model_name="historicalcitizenship",
            name="legal_state_of_residence",
        ),
        migrations.AddField(
            model_name="citizenship",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="citizenship",
            name="state_province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citizenship_state",
                to="common.state",
            ),
        ),
        migrations.AddField(
            model_name="historicalcitizenship",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="historicalcitizenship",
            name="state_province",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.state",
            ),
        ),
    ]
