# Generated by Django 5.0.3 on 2024-08-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_alter_historicaluserdocument_use_and_more"),
        ("profile_app", "0016_remove_citizenship_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalvisa",
            name="issuing_country",
        ),
        migrations.RemoveField(
            model_name="visa",
            name="issuing_country",
        ),
        migrations.AddField(
            model_name="historicalvisa",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="historicalvisa",
            name="state_province",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.state",
            ),
        ),
        migrations.AddField(
            model_name="visa",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="visa",
            name="state_province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visa_state",
                to="common.state",
            ),
        ),
    ]
