# Generated by Django 5.0.3 on 2024-08-29 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college_app", "0001_initial"),
        (
            "educational_organizations_app",
            "0007_alter_educationalorganizations_under_category",
        ),
        ("profile_app", "0017_remove_historicalvisa_issuing_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserdetails",
            name="college",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="college_app.college",
            ),
        ),
        migrations.AddField(
            model_name="historicaluserdetails",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="educational_organizations_app.educationalorganizations",
            ),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="college_app.college",
            ),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="educational_organizations_app.educationalorganizations",
            ),
        ),
    ]
