# Generated by Django 5.0.3 on 2024-07-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0001_initial'),
        ('faculty_members_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymembers',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department_app.department'),
        ),
    ]
